name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
        
      - name: Update submodules
        run: git submodule update --init --remote

      - name: Run tests 
        run: make ci

      - name: Upload artifact 
        uses: actions/upload-artifact@v4
        with:
          name: BackstopJS
          path: backstop/backstop_data
        if: always()
